# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=5000']
-   repo: https://github.com/kynan/nbstripout
    rev: 0.4.0
    hooks:
    -   id: nbstripout
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
        -   --in-place
        -   --remove-all-unused-imports
-   repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
        - id: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
