name: Merge Checks

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/run-tests.yaml
    with:
      pkgname: partnet_mobility_utils
      install_string: .[develop,pybullet]
  build_site:
    uses: ./.github/workflows/build-site.yaml
